### PR TITLE
add best practices

### PR DESCRIPTION
**Pull request by alextaaa**

### CODE REVIEW

**Comment by rsercano** [comment]
Hi there,

thank you so much for this PR, would you mind explaining what exactly did you change ?

p.s. I couldn't make it work, it complains about **bson** module. Also I wonder why did you delete `.finished-upgraders` file, since it tells that **You should check it into version control**

**Comment by alextaaa** [comment]
Hello rsercano,
Please, try running this command `npm start`
I updated packages version and package.json for start

**Comment by rsercano** [comment]
@alextaaa but as I can see you've removed `.finished-upgraders` which shouldn't be deleted, and you've removed versions from meteor's package file which shouldn't be done. 

Even though, I've used `npm start` but still got errors about **bson module** and couldn't make it work. 
Could you please try after removing your **node_modules** folder and see results.

And for **momentjs** it stops working in windows, therefore I've downgraded it's bugfix version to **1** intentionally.

**Comment by alextaaa** [comment]
Please add screenshot with error bson

**Comment by alextaaa** [comment]
.finished-upgraders not required file for Meteor app

**Comment by rsercano** [comment]
Here's the error:

```
Unable to resolve some modules:

  "bson" in /D/git/mongoclient-alextaa/server/imports/mongodb/extended_json.js (os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save bson

W20161104-20:31:18.962(2)? (STDERR) C:\Users\Sercan\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161104-20:31:19.055(2)? (STDERR)                                             throw(ex);
W20161104-20:31:19.057(2)? (STDERR)                                             ^
W20161104-20:31:19.058(2)? (STDERR) 
W20161104-20:31:19.059(2)? (STDERR) Error: Can't find npm module 'bson'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20161104-20:31:19.059(2)? (STDERR)     at Object.require (D:\git\mongoclient-alextaa\.meteor\local\build\programs\server\boot.js:200:17)
W20161104-20:31:19.060(2)? (STDERR)     at options.fallback (packages\modules-runtime.js:445:18)
W20161104-20:31:19.061(2)? (STDERR)     at require (packages\modules-runtime.js:112:16)


```

It recommends check in .finished-upgraders with version control in file itself.

**Comment by alextaaa** [comment]
Please check this screenshots 
http://i.imgur.com/njFNyy7.jpg
http://i.imgur.com/Zy9TOUT.jpg

**Comment by rsercano** [comment]
So, you insist on screenshot, here you're:



Also, if you want me to accept this PR please consider:
- Re add `.finished-upgraders`, maybe it's not required but recommended to keep this file in version control:
  > # This file contains information which helps Meteor properly upgrade your
  > # app when you run 'meteor update'. You should check it into version control
  > # with your project.
- Downgrade momentjs  version to **2.15.1** 
- Add versions back to packages file, it's recommended by meteor itself.
- Contribution guide headline is wrong in readme file, since it points out people can contribute by following instructions after executing `npm start` But it's just for starting `mongoclient`.

**Comment by alextaaa** [comment]
@rsercano something wrong with you local dir `D:\git\mongoclient-alextaa`

please do this commands
1. `git clone git@github.com:alextaaa/mongoclient.git`
2. `git checkout issAddBestPractices`
3. `npm start`

I guarantee that works fine )

**Comment by rsercano** [comment]
No success.

**Comment by alextaaa** [comment]
It's really strange

Sorry ( 

I actually wanted to help you )

I understand what happened ! )))

**Comment by alextaaa** [comment]
not use cmd windows ! )
use only `bash`, for windows amazing bash here https://git-for-windows.github.io/

**Comment by alextaaa** [comment]
you can check on Linux my code
The code start up without error )

**Comment by rsercano** [comment]
Hi @alextaaa 

gotta check this asap, but meanwhile please consider what I've typed down in previous comments for me to accept this PR.

**Comment by rsercano** [comment]
as part of your PR, I've changes some parts of mongoclient thank you

**Pull request closed without merging**
