### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by alu**
Add Dockefile for [this issue](https://github.com/rsercano/mongoclient/issues/103).

### CODE REVIEW

**Comment by rsercano** [comment]
Hello, that's great thanks. But I couldn't make it to pass through step:

```
Step 7 : ADD / /opt/mongoclient
 ---> 7f82b4fd2093
Removing intermediate container 249b6f8e3a91
Step 8 : RUN /usr/local/bin/meteor update
 ---> Running in 4a386c9bdccb

```

, It stuck at meteor update command. Could you please have a look at it ? 

Thanks

**Comment by rsercano** [comment]
After a while it throws:

```
Step 8 : RUN /usr/local/bin/meteor update
 ---> Running in f5daa360eb64
npm-container: updating npm dependencies -- mongodb, mongodb-backup,
mongodb-restore, tunnel-ssh, cheerio, winston...

/root/.meteor/packages/templating/.1.1.9.18yb8nj++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: EXDEV, rename '/opt/mongoclient/packages/npm-container/.npm/package'
The command '/bin/sh -c /usr/local/bin/meteor update' returned a non-zero code: 8
```

Can it be about fedora ?

**Comment by alu** [comment]
Thanks for check this PR.

Actually, `meteor update` command takes 2-4 minutes (depends on each enviroment).

Below output is docker build (always with  `time`  RUN operaions) output on my enviroment.
https://gist.github.com/alu/b5d781bd4215ca0326c62d0a44251af7

The exception will always occur?

**Comment by rsercano** [comment]
It's my pleasure. Thanks for the file.

In ubuntu it sometimes stuck (I've waited for 15 minutes at least) and sometimes throws this exception. 
In windows it always stuck.

Cheers

**Comment by rsercano** [comment]
I've removed local directory and it worked !! Thanks !

**Pull request merged**
