### PR TITLE
mongodb-backup/restore: updates

### PR DESCRIPTION
**Pull request by hex7c0**
mongodb-backup@1.6.x introduce stream cursor
https://github.com/hex7c0/mongodb-backup/issues/11

### CODE REVIEW

**Comment by hex7c0** [comment]
meteor does not support tilde operator.
this PR is just an update of deps

**Comment by rsercano** [comment]
Thank you so much :)

**Comment by hex7c0** [comment]
wait :)
I'm writing a new commit for fix `must declare exact version of dependency`

**Comment by rsercano** [comment]
Could you please make a new PR thanks :) I reverted other back

**Pull request merged**
