### PR TITLE
Update meteor version

### LINKED ISSUE #37: Meteor 1.3 Migration

### PR DESCRIPTION
**Pull request by ghost**
The project is updated to the last version of Meteor with Node 0.10.x, and it seems to run just fine.

### CODE REVIEW

**Comment by rsercano** [comment]
Hello,

thank you so much for this PR, have you tried this with removing .meteor/local cache storages ?

Cheers

**Comment by ghost** [comment]
Yes, I did try to remove .meteor/local, and it seems to run just fine.

The latest commit I made 'Update to Meteor 1.4.0.1' looks more extensive than it actually is. The ES2015 syntax introduced by the 'ecmascript' package doesn't play well with global variables, like jQuery and the corresponding plugins, so they initially caused warnings.

I solved the issues by removing the plugins from /client/packages and adding their respective atmosphere wrapper packages (TODO: load them directly from npm). This is why so many files are modified in the latest commit. 

I think it makes a lot of sense to remove the 3rd-party libs from the repository anyway.

**Comment by rsercano** [comment]
Oh thank you. I totally agree with you about 3rd party libs, I'm checking this PR now

**Comment by rsercano** [comment]
Hi there,

unfortunately I couldn't make this PR work, Here are the logs:

```
Unable to resolve some modules:

  "jquery" in
/D/Calismalar/Meteor/mongoclient-PR138/client/plugins/dataTables/datatables.min.js
(web.browser)
  "mongodb" in
/D/Calismalar/Meteor/mongoclient-PR138/lib/routers/file_management/download_file.js
(web.browser)
  "datatables.net" in
/D/Calismalar/Meteor/mongoclient-PR138/client/plugins/dataTables/datatables.min.js
(web.browser)
  "datatables.net-bs" in
/D/Calismalar/Meteor/mongoclient-PR138/client/plugins/dataTables/datatables.min.js
(web.browser)
  "datatables.net-buttons" in
/D/Calismalar/Meteor/mongoclient-PR138/client/plugins/dataTables/datatables.min.js
(web.browser)
  "datatables.net-responsive" in
/D/Calismalar/Meteor/mongoclient-PR138/client/plugins/dataTables/datatables.min.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save jquery mongodb datatables.net
datatables.net-bs datatables.net-buttons datatables.net-responsive


Unable to resolve some modules:

  "mongodb" in
/D/Calismalar/Meteor/mongoclient-PR138/server/mongodb/helper.js
(os.windows.x86_32)
  "winston" in
/D/Calismalar/Meteor/mongoclient-PR138/server/internal/logging/winston.js
(os.windows.x86_32)
  "mongodb-restore" in
/D/Calismalar/Meteor/mongoclient-PR138/server/mongodb/methods_dump_restore.js
(os.windows.x86_32)
  "mongodb-backup" in
/D/Calismalar/Meteor/mongoclient-PR138/server/mongodb/methods_dump_restore.js
(os.windows.x86_32)
  "cheerio" in
/D/Calismalar/Meteor/mongoclient-PR138/server/mongodb/methods_user_management.js
(os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save mongodb winston mongodb-restore mongodb-backup
cheerio

W20160730-17:45:29.635(3)? (STDERR) C:\Users\RSercan\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160730-17:45:29.698(3)? (STDERR)                         throw(ex);
W20160730-17:45:29.699(3)? (STDERR)                         ^
W20160730-17:45:29.699(3)? (STDERR) 
W20160730-17:45:29.699(3)? (STDERR) Error: Can't find npm module 'winston'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160730-17:45:29.699(3)? (STDERR)     at Object.Npm.require (D:\Calismalar\Meteor\mongoclient-PR138\.meteor\local\build\programs\server\boot.js:203:17)
W20160730-17:45:29.699(3)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160730-17:45:29.699(3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
W20160730-17:45:29.700(3)? (STDERR)     at meteorInstall.server.internal.logging.winston.js (server/internal/logging/winston.js:4:10)
W20160730-17:45:29.700(3)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160730-17:45:29.700(3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160730-17:45:29.700(3)? (STDERR)     at D:\Calismalar\Meteor\mongoclient-PR138\.meteor\local\build\programs\server\app\app.js:2067:1
W20160730-17:45:29.700(3)? (STDERR)     at D:\Calismalar\Meteor\mongoclient-PR138\.meteor\local\build\programs\server\boot.js:297:10
W20160730-17:45:29.700(3)? (STDERR)     at Array.forEach (native)
W20160730-17:45:29.701(3)? (STDERR)     at Function._.each._.forEach (C:\Users\RSercan\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
=> Exited with code: 1
```

As I mentioned when you remove old build's cache directories, I'm pretty sure you'll encounter these. Try to checkout your fork and re-build.

Cheers

**Comment by ghost** [comment]
Did you run `meteor npm install`? I get the same errors if I delete the node_modules folder.

**Comment by rsercano** [comment]
Sorry my bad, but now it throws this:

```
W20160730-22:16:14.572(3)? (STDERR) D:\Calismalar\Meteor\mongoclient-PR138\.meteor\local\build\programs\server\shell-server.js:15
W20160730-22:16:14.645(3)? (STDERR) require("meteor-promise").makeCompatible(Promise, require("fibers"));
W20160730-22:16:14.646(3)? (STDERR)                           ^
W20160730-22:16:14.646(3)? (STDERR) 
W20160730-22:16:14.646(3)? (STDERR) TypeError: require(...).makeCompatible is not a function
W20160730-22:16:14.646(3)? (STDERR)     at Object.<anonymous> (D:\Calismalar\Meteor\mongoclient-PR138\.meteor\local\build\programs\server\shell-server.js:15:27)
W20160730-22:16:14.646(3)? (STDERR)     at Module._compile (module.js:409:26)
W20160730-22:16:14.647(3)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160730-22:16:14.647(3)? (STDERR)     at Module.load (module.js:343:32)
```

**Comment by ghost** [comment]
It sounds like a windows specific migration issue to 1.4. I found another instance of this error in the forum:
https://forums.meteor.com/t/running-meteor-meteor-1-4-beta-3-on-win-7-os/25620#!

**Comment by ghost** [comment]
I have tracked the issue an old version of meteor-promise npm package. The devDependency "chimp" is relying on such package and it might be causing the issue.

**Comment by rsercano** [comment]
Alright then, since mongoclient doesn't have tests yet, I'll remove this dependency and try it.

**Comment by rsercano** [comment]
Nicely done, but now it has this browser error: `Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Have you tried to connect any database after upgrade ?

**Comment by ghost** [comment]
I found that jquery:2.2.0 does the trick. I have successfully connected a database.

**Comment by rsercano** [comment]
Okay, it works but there are a lot of view changes (bootstrap execute button has gone smaller, jsoneditor changed, ) and most importantly check-boxes disappeared. (Check the connection screen and you'll realize it.)

**Comment by ghost** [comment]
I have re-added the stylesheets from iCheck and jsoneditor that were placed in /client/plugins. The check-boxes are back again as far as I can tell.

**Comment by ghost** [comment]
It appears that the jsoneditor atmosphere package create the classes on the dom elements different, so the old stylesheet didn't change the visuals.

The visuals can be tweaked, but the most important is that everything at least work properly after this migration. Do you find anything else that doesn't work at all?

**Comment by rsercano** [comment]
I'm checking again, thanks for your great efforts

**Comment by rsercano** [comment]
It seems way better, if you can resolve style problems, I would gladly accept this PR.

This is old view:
old_view

This is the new one:

new

Could you please check this ? And of course jsoneditor as you mentioned

**Comment by ghost** [comment]
The execute button is now full width again, and the JSON editor is now minimalistic and green again.

It appeared that the jsoneditor atmosphere package was a little outdated, so the issue was resolved by using the npm package instead.

**Comment by rsercano** [comment]
Thank you so much, but still there are issues.
- Ladda buttons seem really weird while during loading. 
- Chosen combo-boxes still seems gray, I guess theme's styles are not applying.
- I had a console error on user managament section, but then I lost where it is.
- All data tables seem weird. (Searchbox seems lost its style, previous and next buttons seem to be converted to link)
- I had a browser console error on user management section and then I lost where it'is needs to clarify it.
- In user-management section chosen combo-boxes had adding and removing feature but it doesn't seem to be working correctly now. 

Still having these issues and I guess some datatable columns are not adjusted but this is not related about this upgrade.

**Comment by ghost** [comment]
All these issues are caused by deprecated atmosphere packages, so it would definitely be more clever to use the updated npm versions instead.

I unfortunately find it difficult to load the jQuery plugins from npm into a global jQuery object. The plugins are currently just dumped in 'client' and exist globally, but ES2015 imply a more modular structure where the plugins are imported with `import Plugin from 'plugin'`.

I don't have the time to resolve this right now, but maybe you could have a look at it?

**Comment by rsercano** [comment]
Alright, thanks for your great efforts again. I will queue this asap. Meanwhile could you please rebase your fork and commit.

**Comment by ghost** [comment]
Sure. Could you clarify what steps I need to take in order to rebase correctly? I have done it several times before, and I use SourceTree, but the commits are already on the master branch - so should they end up in another branch?

**Comment by rsercano** [comment]
There are only two commits ahead from your fork, and it seems to be conflicting because of it. It should be on master branch. Or instead you can merge these commits to your fork

**Comment by ghost** [comment]
Ah, okay. I have merged the new commits to my fork.

**Comment by rsercano** [comment]
Additionally it seems that somehow I cant use autocomplete feature in this PR

**Comment by ghost** [comment]
Maybe it's easier to digest this update in smaller pieces.

The first commit I made called: Run "meteor update --release 1.3.5.1", didn't break anything as far as I know. 

Could you maybe double-check that, and merge that part?

**Comment by ghost** [comment]
I'm making a new pr ( #148  )  just for updating to 1.3.5.1

**Comment by rsercano** [comment]
I'll gladly check that.

**Pull request closed without merging**
