### PR TITLE
Update to Meteor 1.4.0.1

### PR DESCRIPTION
**Pull request by ghost**
Update Node from 0.10.x to 4.4.7
#### Procedure
- Run `meteor update` to update meteor to 1.4.0.1
- Update individual meteor packages to their newest version
- **Be aware that this step wipes the local database.** Run `meteor reset` because this version of Meteor contains a newer version of mongo than Meteor 1.3.5.1 or earlier.

### CODE REVIEW

**Comment by rsercano** [comment]
Thank you ! Could you please rebase (merge my latest commits to your fork) your code base ?

**Comment by ghost** [comment]
Btw. for the travis build. Now that meteor bundles with npm and node, could those be used instead of downloading a separate set of npm and node?

**Comment by rsercano** [comment]
Indeed, I already removed scripts and not downloading any separate package just meteor.

**Comment by rsercano** [comment]
Thanks !

**Pull request merged**
